Noahcaldwell/halloffame
Sea-Quail/finalProj pull request #42
Opened 2024-11-26 06:56 UTC by Debob123

it can update halloffame data

2024-11-26 19:46 UTC, ickoxii commented on .DS_Store
Add .DS_Store to the `.gitignore` file. We don't want to track this. After you add .DS_Store to the gitignore, run `git rm --cached \`find . -name \.DS_Store\`` to stop tracking these files

2024-11-26 19:48 UTC, ickoxii commented on .Rhistory
likewise, add `.Rhistory` to the gitignore and remove tracking with `git rm --cached .Rhistory`

2024-11-26 19:48 UTC, cateburglar commented on dbSetup/services/halloffame_csv_service.py
> +        print(update_fielding_from_csv(csv_file_path))
LOL you should change this function name and the function definition to the correct one. (update_halloffame_from_csv). its nbd but just for consistency

2024-11-26 19:49 UTC, ickoxii commented on .python-version
After pulling in main, you just have to run `git rm --cached .python-version`

2024-11-26 20:01 UTC, cateburglar commented
looks good, just a note that u dont have the implementation of batting stats view? like the actual calculation of the stats and "reading in" of data. might be coming in a different PR just wanted to make a note.

2024-11-26 20:11 UTC, ickoxii commented
> looks good, just a note that u dont have the implementation of batting stats view? like the actual calculation of the stats and "reading in" of data. might be coming in a different PR just wanted to make a note.

Looks like he does have a batting stats view branch but its not in a pr yet

2024-11-27 03:50 UTC, ickoxii commented
***DO NOT MERGE THIS YET***
Lots of merge conflicts in `apps` to go through still

2024-11-28 02:27 UTC, ickoxii commented
> _**DO NOT MERGE THIS YET**_ Lots of merge conflicts in `apps` to go through still

Merge conflicts fixed. good to go

2024-11-29 17:08 UTC, brendonnewt requested changes

2024-11-29 17:08 UTC, brendonnewt commented on dbSetup/models/tables/__init__.py
> +    f_ZR = Column(SmallInteger, nullable=True)
This needs to be a double.

2024-11-29 17:08 UTC, brendonnewt commented on dbSetup/models/tables/__init__.py
> +    note = Column(String(25), nullable=True)
This needs to be 255.

2024-11-29 17:08 UTC, brendonnewt commented on dbSetup/services/halloffame_csv_service.py
> +            session.merge(halloffame_record)
We figured out we can't use session.merge for things like this. We have to manually check if it exists and modify it's fields.

2024-11-30 02:28 UTC, ickoxii commented on dbSetup/models/tables/__init__.py
> +    note = Column(String(25), nullable=True)
the note attribute in our database is a varchar(25). trying to read any more will throw exceptions

2024-11-30 02:29 UTC, ickoxii commented on dbSetup/models/tables/__init__.py
> +    f_ZR = Column(SmallInteger, nullable=True)
i tried using Double but i dont think thats a valid attribute. sqlalchemy uses the Float keyword

2024-11-30 04:06 UTC, closed without merging