OMFGGGG BRUH THIS TOOK FIVE YEARSDNJSCNEIBUBLELBSBESBSDBUDSFIB
Sea-Quail/finalProj pull request #48
Opened 2024-11-28 03:19 UTC by cateburglar

holy hell this is a ginormous PR. first just let me say that i promise that this is very thoroughly tested

chhanges:
--changed every single table to manually check each entry and to update it or add it accordingly. did this because session.merge did not do what we thought it does-- it was creating duplicates for every single row.
--added unique constraint to every table that didnt have it. i was doing this originally bc i thought it would make session.merge work, but that was incorrect. now its superfluous but im too lazy to go back and undo it lmao soooooo whatever
--added some session.close to files where it was missing
--debugged some tables (i honestly cant remember which, but just some of them ended up being constructed wrong and i had to change some of the table definitions and stuff)

AFTER THIS PR IS APPROVED AND MERGED, EVERYONE MUST DELETE SEAQUAIL FROM THEIR LOCAL COMPUTER AND RE-INPUT AND RE-UPDATE ALL DATA!!!!!!!!!!!!!!!!!!!

2024-11-28 03:57 UTC, brendonnewt requested changes
I'm asking Icko to double check the last half of this, but please add my lgidwinner and lgidloser back. Please try to keep me informed when you plan on making changes to the database in a pr.

2024-11-28 03:57 UTC, brendonnewt commented on dbSetup/models/tables/__init__.py
> +    school_name = Column(String(255), nullable=False)
It doesn't matter if they are/aren't null. The database allows it, so we should too.

2024-11-28 03:57 UTC, brendonnewt commented on dbSetup/models/tables/__init__.py
> -    lgIDwinner = Column(String(3), ForeignKey("leagues.lgID"), nullable=False)
Why you delete my foreign keys :(

2024-11-28 08:18 UTC, cateburglar commented on dbSetup/models/tables/__init__.py
> -    lgIDwinner = Column(String(3), ForeignKey("leagues.lgID"), nullable=False)
because it wasnt letting me process any requests with seriespost with these bc the already existing tables in the databe dont contain these

2024-11-28 08:25 UTC, cateburglar commented on dbSetup/models/tables/__init__.py
> +    school_name = Column(String(255), nullable=False)
i mean idk if i agree with that logic- we are allowed to make changes to the database's structure so long as its an improvement, and allowing these to be null doesnt make sense bc 
A) it never happens (u would never be given just a school name without the location)
B) multiple schools can have the same name and id (like how there are 3 columbia colleges irl--dont know if these schools are in our database, i just mean in theory).

but it would be helpful to hear why u think its better practice to allow them to be null

2024-11-28 08:28 UTC, cateburglar commented on dbSetup/models/tables/__init__.py
> +    school_name = Column(String(255), nullable=False)
also however im now realizing that if we DID change them to be non nullable we would have to alter table

sorry i was like half braindead whilst doing this pr

2024-11-28 08:29 UTC, cateburglar commented on dbSetup/models/tables/__init__.py
> -    lgIDwinner = Column(String(3), ForeignKey("leagues.lgID"), nullable=False)
ok all good my b

2024-11-28 17:30 UTC, brendonnewt commented on dbSetup/models/tables/__init__.py
> +    school_name = Column(String(255), nullable=False)
If you can guarantee that there isn't any rows in the table that aren't missing that information then you can change it. I'm just cautious of making significant changes like that as the information we have currently conforms to those standards. If you want to change it, please include in the change log the SQL that you used to update the fields/constraints.

2024-11-28 17:46 UTC, cateburglar commented on dbSetup/models/tables/__init__.py
> +    school_name = Column(String(255), nullable=False)
ya i checked whether any of the existing columns were null but they were not! ill make a note

2024-11-29 01:44 UTC, ickoxii commented
There seems to be some issue with processing the Batting table but not a major error. The major error happens when modifying the Draft table. The table does not exist so I'm guessing it's because draft is not present in the seaquail dump that we load during the beginning of the action.

2024-11-29 02:02 UTC, ickoxii commented
> There seems to be some issue with processing the Batting table but not a major error. The major error happens when modifying the Draft table. The table does not exist so I'm guessing it's because draft is not present in the seaquail dump that we load during the beginning of the action.

I'm going to work on creating that table then generating a new dump to load in

2024-11-29 04:39 UTC, brendonnewt approved these changes
This is too many files for me to guarantee it works, but it looks good. If you've tested it locally and it works for everything besides draft and nohitters, lgtm

2024-11-29 04:39 UTC, brendonnewt commented on dbSetup/services/appearances_csv_service.py
> +def retry_on_deadlock(tries=3, delay=2):
Based

2024-11-29 04:39 UTC, brendonnewt commented on dbSetup/services/batting_csv_service.py
> +def retry_on_deadlock(tries=3, delay=2):
Based pt. 2

2024-11-29 04:41 UTC, brendonnewt commented on dbSetup/services/people_csv_service.py
> +            existing_entry = (
This works, but just know that session.merge actually worked here and you didn't need to do all this work

2024-11-29 17:10 UTC, merged