Noahcaldwell/batting stats view
Sea-Quail/finalProj pull request #62
Opened 2024-12-02 22:12 UTC by Debob123

# Overview
added script that creates batting_stats_view for database with mostly accurate data

## Changes
added view file in dbsetup directory that includes init.py file that initializes view and script that creates view 

## Proof of Life
Loaded query into SQL to prove that it creates view correctly and selected specific values from houston astros in 2022 to see if it pulled correct data.

2024-12-02 23:39 UTC, cateburglar commented on dbSetup/models/views/batting_stats_view.py
> +    JOIN player p ON b.playerID = p.playerID
it's "JOIN people p..." not "player p"

2024-12-02 23:43 UTC, cateburglar commented on dbSetup/models/views/batting_stats_view.py
> +session.commit()
this does not execute the sql. you need to do session.execute(----) first. as your code stands right now, nothing changes in the database

2024-12-02 23:45 UTC, cateburglar commented on dbSetup/models/views/batting_stats_view.py
> +create_view_query = """
this query is not functional-- i'm not going to go through and debug it all myself so could you test this using the database on your terminal and then make the necessary changes

2024-12-03 00:18 UTC, ickoxii commented on dbSetup/models/views/batting_stats_view.py
> +session.commit()
update this query with whatever was in that sql file you loaded earlier. that seemed to calculate stats

2024-12-03 00:18 UTC, ickoxii commented on dbSetup/models/views/batting_stats_view.py
> +create_view_query = """
update this query with whatever was in that sql file you loaded earlier. that seemed to calculate stats

2024-12-03 00:19 UTC, ickoxii commented on dbSetup/models/views/batting_stats_view.py
> +session.commit()
take a look at the create_views_service file in main to get an idea of how i loaded my views.

2024-12-03 00:20 UTC, ickoxii commented on app/routes/grid_routes.py
> +<<<<<<< HEAD
fix merge conflicts

2024-12-03 00:20 UTC, ickoxii commented on app/static/css/base.css
> +<<<<<<< HEAD
fix merge conflicts

2024-12-03 00:22 UTC, ickoxii commented on app/templates/base.html
> +<<<<<<< HEAD
more conflicts

2024-12-03 00:22 UTC, ickoxii commented on app/templates/immaculate_grid.html
> +<<<<<<< HEAD
fix conflicts

2024-12-03 05:32 UTC, brendonnewt requested changes
I ran some tests using this, and I ran into a few issues. Firstly, I don't think the joins are joining 1-to-1 as there are multiple entries for each player. Secondly, the wOBA, wRCplus, and BsR are giving incorrect output. I'm not sure about the rest, these are just the first I noticed. 

Please try select * from battingstatsview where name = 'Steven Kwan' and yearid = 2022;

Also, if you could structure the playerid, teamID, yearID, stint, etc the same as Icko that would be great for consistency. We don't really need the player name (as multiple players can have the same name) or the team_name (that can be retrieved using the yearid and teamID). Furthermore, try to follow a similar naming scheme to his as well as that matches the rest of the database, and we want these views to be usable without having to go check their field names all the time.

To summarize, there are duplicates, some calculations are incorrect, and the fields need to be tweaked to match the present dbms conventions.

2024-12-03 05:32 UTC, brendonnewt commented on app/static/css/grid.css
> +:root {
I'm assuming Icko did this, but this is the wrong file. The base.css should be in base.css, not grid.css

2024-12-03 15:46 UTC, brendonnewt commented
> I ran some tests using this, and I ran into a few issues. Firstly, I don't think the joins are joining 1-to-1 as there are multiple entries for each player. Secondly, the wOBA, wRCplus, and BsR are giving incorrect output. I'm not sure about the rest, these are just the first I noticed.
> 
> Please try select * from battingstatsview where name = 'Steven Kwan' and yearid = 2022;
> 
> Also, if you could structure the playerid, teamID, yearID, stint, etc the same as Icko that would be great for consistency. We don't really need the player name (as multiple players can have the same name) or the team_name (that can be retrieved using the yearid and teamID). Furthermore, try to follow a similar naming scheme to his as well as that matches the rest of the database, and we want these views to be usable without having to go check their field names all the time.
> 
> To summarize, there are duplicates, some calculations are incorrect, and the fields need to be tweaked to match the present dbms conventions.

Coming back to this, if they have zero plate appearances (ie. Pitchers), they shouldn't be in this view. Be sure to only include batters in the batting stats please.

2024-12-03 18:18 UTC, cateburglar commented
> I ran some tests using this, and I ran into a few issues. Firstly, I don't think the joins are joining 1-to-1 as there are multiple entries for each player. Secondly, the wOBA, wRCplus, and BsR are giving incorrect output. I'm not sure about the rest, these are just the first I noticed.
> 
> Please try select * from battingstatsview where name = 'Steven Kwan' and yearid = 2022;
> 
> Also, if you could structure the playerid, teamID, yearID, stint, etc the same as Icko that would be great for consistency. We don't really need the player name (as multiple players can have the same name) or the team_name (that can be retrieved using the yearid and teamID). Furthermore, try to follow a similar naming scheme to his as well as that matches the rest of the database, and we want these views to be usable without having to go check their field names all the time.
> 
> To summarize, there are duplicates, some calculations are incorrect, and the fields need to be tweaked to match the present dbms conventions.

no please keep name in it!!! the point of the batting stats view was to be able to have all the info we wanted to display in one place , and keeping name in this view makes it easier for the depthchart/team summary

2024-12-03 20:40 UTC, ickoxii commented on dbSetup/services/create_views_service.py
> +            (((0.69 * b.b_BB) + (0.72 * b.b_HBP) + (0.88 * (b.b_H - (b.b_2B + b.b_3B + b.b_HR))) + (1.24 * b.b_2B) + (1.56 * b.b_3B) + (2.0 * b.b_HR)) / (b.b_AB + b.b_BB + b.b_HBP + b.b_SH + b.b_SF))
wOBA can be 0.00, not null

2024-12-03 20:41 UTC, ickoxii commented on dbSetup/services/create_views_service.py
> +            ((((((0.69 * b.b_BB) + (0.72 * b.b_HBP) + (0.88 * (b.b_H - (b.b_2B + b.b_3B + b.b_HR))) + (1.24 * b.b_2B) + (1.56 * b.b_3B) + (2.0 * b.b_HR)) / (b.b_AB + b.b_BB + b.b_HBP + b.b_SH + b.b_S
wRCplus, 0 has an actual meaning because it allows negative values. However, it does allow null values

2024-12-03 20:44 UTC, ickoxii commented on dbSetup/services/create_views_service.py
> +            batting b
fuck it natural join everything

2024-12-03 20:44 UTC, ickoxii commented on dbSetup/services/create_views_service.py
> +            batting b
if that doesn't work join using explicit values (all common attributes)

2024-12-03 20:46 UTC, ickoxii commented on dbSetup/services/create_views_service.py
> +            teams t ON b.teamID = t.teamID AND b.yearID = t.yearID
no need to join teams

2024-12-04 04:28 UTC, closed without merging