Noahcaldwell/batting stats view
Sea-Quail/finalProj pull request #77
Opened 2024-12-07 18:45 UTC by Debob123

# Overview
added wrc_plus to batting stats view, added playing time calcuations for batting stats and pitching stats

## Changes
added section to SQL query for pitching stats view and batting stats view to include playing time. Added WarData ORM and functions to read in warData table to batting stats view. Also added csv file containing war and wrcplus info to dbSetup/static/csv

## Proof of Life
(I don't remember what proof of life means)

2024-12-07 19:43 UTC, brendonnewt commented
> # Overview
> added wrc_plus to batting stats view, added playing time calcuations for batting stats and pitching stats
> 
> ## Changes
> added section to SQL query for pitching stats view and batting stats view to include playing time. Added WarData ORM and functions to read in warData table to batting stats view. Also added csv file containing war and wrcplus info to dbSetup/static/csv
> 
> ## Proof of Life
> (I don't remember what proof of life means)

Proof of life means some evidence that the feature/bug-fix does what it is intended to do. So some sort of proof that it's been tested and works.

2024-12-07 21:32 UTC, brendonnewt requested changes
I can't check this because it has syntax errors. Please make sure to run the script and make sure it works so that I can check if the values are coming out as expected. I also left some other comments about things I would like to see changed.

2024-12-07 21:32 UTC, brendonnewt commented on dbSetup/models/tables/__init__.py
> +
Why so many lines? 😭

2024-12-07 21:32 UTC, brendonnewt commented on dbSetup/services/create_battingstats_view.py
> +        WarData br ON CONCAT(p.nameFirst, ' ', p.nameLast) = br.Name AND b.yearID = br.yearID
This isn't going to do what you want. Players can have the same name, please use playerID for all joins as those are unique.

2024-12-07 21:32 UTC, brendonnewt commented on dbSetup/services/create_battingstats_view.py
> +    Name = Column(String(255), nullable=False)
You don't have to include the name if all you're doing is joining it to the existing battingstatsview but you do need the playerID

2024-12-07 21:32 UTC, brendonnewt commented on dbSetup/services/batting_csv_service.py
>      # Aggregate results
results variable needs to be changed to batting_results

2024-12-07 21:32 UTC, brendonnewt commented on dbSetup/services/create_battingstats_view.py
> +               WHERE b2.yearID = b.yearID AND b2.teamID = b.teamID)) * 100 AS b_Playing_Time
Missing a comma here

2024-12-07 22:42 UTC, ickoxii commented
> > # Overview
> > added wrc_plus to batting stats view, added playing time calcuations for batting stats and pitching stats
> > ## Changes
> > added section to SQL query for pitching stats view and batting stats view to include playing time. Added WarData ORM and functions to read in warData table to batting stats view. Also added csv file containing war and wrcplus info to dbSetup/static/csv
> > ## Proof of Life
> > (I don't remember what proof of life means)
> 
> Proof of life means some evidence that the feature/bug-fix does what it is intended to do. So some sort of proof that it's been tested and works.

i.e. screenshots, what you did to validate your implementation, etc.

2024-12-08 20:01 UTC, cateburglar commented on dbSetup/services/create_battingstats_view.py
> +class WarData(Base):
why are you defining wardata twice (in views/init and also here)? only define it once, and then import it as needed. additionally, your definition in views/init does not match this definition.

2024-12-08 20:06 UTC, cateburglar commented on dbSetup/services/create_views_service.py
remove this file from this commit -- we deleted this file bc its unnecessary / repetitive

2024-12-08 20:07 UTC, cateburglar commented on dbSetup/services/create_pitchingstats_view.py
remove this file from your commit as well -- icko created a p_playing_time already

2024-12-08 20:10 UTC, cateburglar requested changes
see my comments

2024-12-09 02:32 UTC, cateburglar commented on dbSetup/services/create_battingstats_view.py
> +
why did u change this? this is incorrect-- it needs to be the version that u deleted bc sometimes b_PA is null and that doesnt necessarily mean that that given player should be excluded

2024-12-09 03:02 UTC, Debob123 commented on dbSetup/services/create_battingstats_view.py
> +
I'm sorry i didn'tthink that was needed. I readded it.

2024-12-09 06:03 UTC, closed without merging